### ISSUE TITLE
Can't have the app open and use it to autofill

### ISSUE THREAD

**Issue by Pixel-Minions** [bitwarden/android#4062] opened 2024-10-10 15:30 UTC
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open the app in Android 14
2. Open a browser or an app
3. Try to use bitwarden, it will load and load
4. If you close the bitwarden app and try again, now it works.

### Expected Result

I should be able to have the app open and use it any other app.

### Actual Result

Only when the app is closed, I can use it in another app or browser in Android 14.

### Build Version

v2024.9.0

### Environment Details

Device: S24
Android version: 14

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment] 2024-10-11 13:54
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by Pixel-Minions** [comment] 2024-10-12 05:49
Yes, it looks the same.

**Comment by spqx1337** [comment] 2024-10-22 11:13
I can confirm the issue exists (Android 15 Beta, Pixel 7 Pro)

**Comment by maszaa** [comment] 2024-10-30 17:06
Exists in 2024.10.2

**Comment by sgrit** [comment] 2024-11-07 05:55
Exists in 2024.11.1
Android 15
Pixel7a

When facing load forever, closing the browser and open bitwarden app and then load completed. After that, come back to the browser and try to autofill again, then it works.

**Comment by fersingb** [comment] 2024-11-08 01:44
Similar issue happening here on s23, android 14.

In my case, I've 2 bitwarden accounts and switching between accounts seems to solve the loading issue.

Here are the steps:
- use the auto-fill feature
- unlock bitwarden, loading bug occurs
- tap on the account switching bouton, select second account, loads without issue
- tap on the account switching button again, go to initial account, loads without issue

**Comment by maxmini1** [comment] 2024-11-08 08:07
@Pixel-Minions: there new release should fixe that issue, try close tihis.
https://github.com/bitwarden/android/releases/tag/v2024.11.3

**Comment by fersingb** [comment] 2024-11-08 12:55
Fix confirmed for me

**Closed** 2024-11-08 14:14 UTC
Labels: bug

**Comment by Pixel-Minions** [comment] 2024-11-08 20:19
Thank you! All good
