### ISSUE TITLE
iOS Keyboard not presented when searching from autofill

### ISSUE THREAD

**Issue by ACodingGenie** [bitwarden/android#1114] opened 2020-10-14 02:53 UTC
Whenever you're logging into another app using Bitwarden's autofill feature, the keyboard _sometimes_ does not pop up after authenticating with TouchID inside of the vault. As a result you cannot search through the different entries to find the one you may need to log into that specific application but you have to scroll to find it manually.  I haven't been able to exactly pin-point when this happens or how to repeat it precisely but I've had it happen several times daily whenever I sign into different applications. I will update this issue if I am able to replicate it consistently. 

## Steps To Reproduce
1. Launch an application that you haven't signed into yet.
2. Tap on the username field inside of the app.
3. Hit "Passwords" on your iOS Keyboard and sign into Bitwarden with TouchID or PIN.
4. Hit the magnifying glass icon to search if applicable.
5. Attempt to search for an entry. 

## Expected Result
Bitwarden should allow you to search through entries when utilizing the auto fill functionality on iOS. The keyboard should be displayed on screen and not hidden. 

## Actual Result
Keyboard is hidden and even tapping on the search field makes it not show up. You can't search through the different entries and must scroll and find it manually. 

## Environment

- Device: iPhone SE 2020
- Operating system: iOS 14.0.1
- Build Version: 2.6.1 (278)
- Is this a Beta release? N

## Additional Context
**Note** Haven't found a way to consistently reproduce this issue yet, will update if I can. Others are free to contribute if they notice something. 

EDIT: Was able to reproduce this somewhat repeatedly inside of Brave Browser (Official release) when I tried to sign into "amazon.com" and used the search field inside of the auto fill vault to search for an entry.
EDIT: Can flippin' Apple fix their bugs. SHEEEEEESH :P

**Comment by JaySardhara** [comment] 2020-10-15 05:21
Same issue. Not really sure in which situation this is happening, as it is not consistent but happens quite frequently.

**Comment by evelez7** [comment] 2020-10-27 07:38
I get this as well. iPhone XR, iOS 14.0.1. The keyboard does not show up when going into the list view of accounts, and tapping the search bar does not bring it up.

**Comment by langes** [comment] 2020-11-11 15:22
Experiencing the same issue.

**Comment by optimystified** [comment] 2020-11-21 17:39
I'm experiencing the same issue and it's quite annoying.

**Comment by GlenMerlin** [comment] 2020-11-26 23:24
Can Repro 

iPhone 12 Pro iOS 14.2.1 Bitwarden 2.7.0

**Comment by SergeantConfused** [comment] 2021-01-05 16:04
Thank you all very much for bringing this to our attention. We would be looking into this issue soon.
Please feel free to add more detailed steps on how to reproduce this.

**Comment by joeldroid** [comment] 2021-01-12 09:34
Same issue on iPhone 11 (can reproduce with the same steps) occurs within Safari.
Using iOS 14.3 and latest version of Bitwarden

**Comment by gastlchhh** [comment] 2021-01-13 08:02
Same here iPhone 12 IOS 14.3

**Comment by DarrenVictoriano** [comment] 2021-01-20 03:02
seems like this issue is on iOS 14, other password manager app also sees the same issue.
but it looks like KeePassium was able to pinpoint the cause and came up with a workaround by delaying the biometric prompt.

Link to KeePassium's comment: https://github.com/keepassium/KeePassium/issues/133#issuecomment-735283081

**Comment by keepassium** [comment] 2021-01-20 21:06
@DarrenVictoriano , the cause does seem to be the biometric prompt. Unfortunately, none of my workarounds were completely successful, so that issue is still open.

**Comment by mportune-bw** [comment] 2021-01-20 22:03
@keepassium Thanks for the sanity check.  I was excited to see you discovered a workaround until I realized we already had a similar delay before showing the bio prompt.  Back to the drawing board I go...

**Comment by smani** [comment] 2021-01-24 19:36
I can consistently reproduce "search keyboard not showing up" problem on iOS 13 / 14.3 with both Bitwarden 2.6.1 and 2.8.0 (iPhone X / 12). This mainly happens when logging into some specific apps.

I see three different behaviors App Auto Fill exhibits when using Bitwarden:

1. **Auto Fill Prompt Kind 1:** (first line) for xxx - Bitwarden (second line) username | [Key Icon]  => Just touching the Auto Fill prompt will open Bitwarden sheet, authenticate using Face ID, Bitwarden disappears, the password auto fills like magic. No issue here at all since the "Search vault" sheet isn't shown. E.g. `BoFA` Bank of America App
2. **Auto Fill Prompt Kind 2:** [Key Icon] Passwords => Touching the passwords prompt opens Bitwarden, authenticates using Face ID, shows "Items" sheet with only relevant password entry, just touching the password entry auto fills the password. E.g. Fidelity `NetBenefits` App. Note that in the "Items" sheet, there is a magnifying glass and if we touch it, "Search vault" sheet opens with all the password entries, the keyboard also pops up. If we type few letters, it narrows the list and we can select the appropriate entry to auto fill. This works fine as well (even though we don't need it in this case).
3. **Auto Fill Prompt Kind 3:** [Key Icon] Passwords => Touching the passwords prompt opens Bitwarden, authenticates using Face ID, unlike (2) above, it opens "Search vault" sheet _but keyboard DOES NOT pop up_. Even touch the search input box multiple times doesn't help. Now we are forced to scroll through the list and pick the appropriate entry to auto fill. This is the bug! E.g. `E*TRADE` App.

**Comment by r0e** [comment] 2021-01-27 16:36
I am able to reproduce this issue consistently with the Vanguard mobile app. It prompts with the passwords button and Face ID unlocks Bitwarden but no keyboard pops up, even after tapping inside the search bar.

**Comment by mstoffel-sag** [comment] 2021-07-30 04:38
Great app in general. Thanks for all your effort. Same issue here iPhone 12 mini ios 14.7.1 Bitwarden 2.11.1
Really annoying

**Comment by JanSch** [comment] 2021-08-19 18:45
Same problem here. iPhone 12/14.7.1 and Bitwarden Version: 2.11.1 (704).
It never happens when opening Bitwarden from the homescreen . Only when auto-filling from a non recognised app or site. But then again. It consistently reproduces in the Synology DS photo app

**Comment by andreasba** [comment] 2024-01-27 09:15
I did not have the problem until now - I recently updated to iOS 17.3. Now sure if this is the cuplrit, but it worked before. Closing and restarting the app does not help.

Please fix ASAP it makes the app unusable! @mpbw2

**Comment by vvolkgang** [comment] 2024-06-20 20:55
Issue migrated to https://github.com/bitwarden/mobile/issues/1114

**Closed by vvolkgang** 2024-06-20 20:55 UTC
