### ISSUE TITLE
Password with certain characters is displayed incorrectly in the Android app

### ISSUE THREAD

**Issue by rabindra-harlalka** [bitwarden/android#3110] opened 2024-03-24 02:18 UTC
### Steps To Reproduce

1. Create a login with password that ends with characters `<M`.
2. View the login's password in the Android app. The two characters are rendered only as `M`. The only clue that something is wrong is that M is displayed in the orange color as if it's a special character.
3. Edit the login entry and view the password.
4. It's displayed correctly as `<M`.

### Expected Result

Password must be displayed correctly.

### Actual Result

Password is displayed incorrectly. Unsuspecting users would enter wrong passwords and face various problems.

### Operating System

Android

### Operating System Version

12

### Device

Samsung Galaxy M31s

### Build Version

2024.3.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment] 2024-03-24 10:37
Hi @rabindra-harlalka,

Thank you for your report. I was able to reproduce this behaviour and I have flagged it to our Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by FSchumacher** [comment] 2024-03-26 06:55
If you use some special characters like `_` or `*` after a `<`, those characters will not be displayed either.
It seems, that `>` is an active character, too.

So the password `a<_<1<*<m<><%>q` will be displayed as `a1mq`.
All characters of the passwordwill be shown in edit mode, though.

**Comment by DecMeads** [comment] 2024-03-28 11:42
I have also encountered this bug. I am unable to share a screenshot as the app prevents but I can confirm that I am seeing this same bug in version: 2024.3.0 (9799)

**Comment by mattmelachrinos** [comment] 2024-04-25 16:26
![Screenshot_20240425-122428](https://github.com/bitwarden/mobile/assets/10656062/004fe024-ca11-4dbd-9351-632fcf1e12a9)
![Screenshot_20240425-122424](https://github.com/bitwarden/mobile/assets/10656062/6126351d-2bfd-4e96-9e63-bd666b1d77a3)

**Comment by blut** [comment] 2024-04-29 06:31
Closing https://github.com/bitwarden/mobile/issues/3205 as duplicate

**Comment by AnotherMuggle** [comment] 2024-05-05 16:46
Good, a bug report for this already exists. It almost drove me crazy entering a password exactly as it was displayed and it was not being accepted, because it tas displayed wrong.  I had to copy and paste elsewhere to view the password and realise what was happening.

**Comment by tompipe** [comment] 2024-05-24 04:56
Just logged some info on #3256 before I found this bug. This one's more similar to what I'm experiencing. 

One other thing I noted is that copy/paste contains the full password, so it's only displaying incorrectly, thankfully minimising the impact!

**Comment by dezertrat** [comment] 2024-06-18 19:41
Just to add more fuel to this fire, I wanted to say that I also am experiencing this issue. This is a not-insignificant defect, since sometimes:
- auto-fill doesn't work
- you can't paste into the password field

And so, you have to look at the password and pain-fill the field. 

Any clue as to when this will be resolved? The issue was opened three months ago, and was reported to the engineering team a day after opening.

**Comment by vvolkgang** [comment] 2024-06-20 19:26
Issue migrated to https://github.com/bitwarden/mobile/issues/3110

**Closed by vvolkgang** 2024-06-20 19:26 UTC
Labels: bug
