### ISSUE TITLE
Forwarded Email alias DDG Not working

### ISSUE THREAD

**Issue by zunelol** [bitwarden/android#4387] opened 2024-11-26 15:29 UTC
### Steps To Reproduce

As mentioned before (Ticket #4226 got closed while not actually fixed): 
1. Go to 'Generator'
2. Click on 'Username -> make sure DuckDuckGo is selected as provider and an API Key is saved'
3. Click on 'Generate'

### Expected Result

In the generated username field is a newly generated @duck.com email username.

### Actual Result

An error message "Expect rustls-platform-verifier to be initialized" pops up at the bottom of the app. See video

### Screenshots or Videos

https://github.com/user-attachments/assets/ae27e049-5b9d-4043-a4b7-8c11ff63fea4

### Additional Context

API-Credentials work fine (checked on Bitwarden Extension for Brave on a different device).

For some reason wasnt able to repopen the old issue..

### Build Version

Version: 2024.11.6 (19499)

### What server are you connecting to?

US

### Environment Details

Device: Huawei P30Pro
OS-Version: Android 10 EMUI 12.0.0.219 (C431E3R2P2)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment] 2024-11-26 20:52
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/android/issues/4205

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by cbbit** 2024-11-26 20:52 UTC
Labels: bug
