### ISSUE TITLE
Use biometrics to unlock not open by default

### ISSUE THREAD

**Issue by ySkNight** [bitwarden/android#3825] opened 2024-08-24 00:47 UTC
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. From Android home screen open up Bitwarden(Beta)
2. "Verify master password" screen appear.
3. I have to click on "Use biometrics to unlock"
4. Scan my fingerprint. 
This is current flow,

### Expected Result

Since I already enable use biometrics to unlock, Can the flow be like
1. From Android home screen open up Bitwarden(Beta)
2. "Verify master password" screen appear. Shortly after prompt with fingerprint scanner.
3. Scan my fingerprint. 

Ultimately skip a step by don't have to click on "Use biometrics to unlock"

### Actual Result

biometrics scanner not open up automatically 

### Build Version

2024.8.0(18985)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment] 2024-08-24 00:57
Hi there!

Thank you for your report, it seems like it is a duplicate of this one (https://github.com/bitwarden/android/issues/3724). 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by BBGhub** 2024-08-24 00:57 UTC
Labels: bug
