### ISSUE TITLE
Android auto fill service not working in Chrome Beta

### ISSUE THREAD

**Issue by anstosa** [bitwarden/android#495] opened 2019-05-04 04:45 UTC
The URL is not picked up by the auto fill service in Chrome Beta on Android, it tries to fill based on the app instead.

**Comment by kspearrin** [comment] 2019-05-05 02:22
I am not able to reproduce. Accessibility service seemed to work just fine in my test of logging into GitHub.com with Chrome beta app.

**Comment by anstosa** [comment] 2019-05-05 02:26
Hmm, it's trying to auto fill for me based on `com.chrome.beta`. I'm on Android Q, maybe that's related? But Chrome Stable works fine so that seems unlikely

**Comment by ImjuzCY** [comment] 2019-05-14 02:21
I can confirm this. 
Chrome Beta version: 75.0.3770.28
Bitwarden version: 1.22.0
Android version: 9 Pie

Bitwarden is set as Auto-fill Service in system settings.

**Comment by fruity101079** [comment] 2019-05-14 08:58
I use to have this little bug, the way to bypass it is to go back to the app, click inside the field, and then go again in bitwarden.

**Comment by djohannes** [comment] 2019-06-13 16:24
I have this bug, too - but not just with Bitwarden. There is no password manager for me that works with Chrome Beta.

**Comment by quthla** [comment] 2019-06-18 11:02
Possible duplicate of https://github.com/bitwarden/mobile/issues/242 and https://github.com/bitwarden/mobile/issues/310

Not sure if it can be fixed but is known for almost 1.5 years already. Maybe @kspearrin can shed some light on this?

**Comment by glennbnr** [comment] 2019-07-16 19:44
I also have this issue on Microsoft Edge on Android 9.
Samsung S9+
Android 9 
Edge Version 42.0.22.3812 (latest in Play store as of 16/07/19)
Bitwarden 2.1.0 (latest in Play store as of 16/07/19)

I'd say the issues are related, but if you want me to move this to a separate issue I will do.

**Comment by liamfoneill** [comment] 2020-01-06 18:56
I have the same issue except for Microsoft Edge on Android 10. I tries to match for 'com.microsoft.emmx' rather than detect the URL from the browser.

**Comment by Coryrichter94** [comment] 2020-01-06 18:58
I have the same issue as well with Microsoft edge on Android

**Comment by vvolkgang** [comment] 2024-06-20 20:59
Issue migrated to https://github.com/bitwarden/mobile/issues/495

**Closed by vvolkgang** 2024-06-20 20:59 UTC
