### ISSUE TITLE
Error while generating email alias with SimpleLogin integration

### ISSUE THREAD

**Issue by thomaspinkas** [bitwarden/android#4225] opened 2024-11-03 14:30 UTC
### Steps To Reproduce

1. Open the Bitwarden app.

2. Go to the generator and select "Forwarded email alias."

3. Set the service to "SimpleLogin" and enter the required API key.

4. Attempt to generate a new email alias.

### Expected Result

The app should generate a new email alias using the SimpleLogin service without errors.

### Actual Result

An error message is displayed stating: "Error sending request for URL (https://app.simplelogin.io/api/alias/random/new?hostname=https://stabilityai.us.auth0.com)"

### Screenshots or Videos

![Screenshot_20241103-151909](https://github.com/user-attachments/assets/8b433e58-0bbd-4c18-8d24-f093135986a6)

### Build Version

2024.10.2 (19397)

### What server are you connecting to?

EU

### Environment Details

Device: Google Pixel 9 Pro XL

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by noodlejetski** [comment] 2024-11-04 12:51
https://github.com/bitwarden/android/issues/4205#issuecomment-2448233914

**Comment by cbw23** [comment] 2024-11-04 16:34
Hi there!

Thank you for your report, it seems like it is a duplicate of this one #4205 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by cbw23** 2024-11-04 16:34 UTC
Labels: bug
