### ISSUE TITLE
Android Biometrics Popup

### ISSUE THREAD

**Issue by Araxeus** [bitwarden/android#3789] opened 2024-08-20 16:45 UTC
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Enable "Unlock with Biometrics"
2. Close app
3. Open app

### Expected Result

Expected: When opening the app with biometrics enabled, the fingerprint and/or facial recognition popup should open

### Actual Result

Result: No popup is shown, user first has to click on "Use biometrics to unlock"

### Additional Context

This only started occurring after updating to https://github.com/bitwarden/android/releases/tag/v2024.8.0 (released aug 20, 2024)

previous version worked fine

### Build Version

2024.8.0 (18985)

### Environment Details

- Device: Xiaomi POCO X6 Pro
- OS: HyperOS 1.0.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Araxeus** [comment] 2024-08-20 16:46
Please notice that it worked fine for me before #3728 and broke after it!

**Comment by djsmith85** [comment] 2024-08-20 19:03
@Araxeus Thank you for your report.

This is a duplicate of https://github.com/bitwarden/android/issues/3724 and the changes you mention are not yet included in the latest release. These will be included in the next release.

Closing this now.

**Closed by djsmith85** 2024-08-20 19:03 UTC
Labels: bug

**Comment by Araxeus** [comment] 2024-08-20 19:29
Then im very confused why did it work before I updated to the version you released **today**

**Comment by djsmith85** [comment] 2024-08-20 19:38
> Then im very confused why did it work before I updated to the version you released **today**

Because https://github.com/bitwarden/android/pull/3601, which likely caused it, is included in the 2024.8.0 release, but as mentioned a [fix](https://github.com/bitwarden/android/pull/3728) is currently in QA and will be included in the next release.
