### ISSUE TITLE
The biometric lock screen does not open automatically

### ISSUE THREAD

**Issue by Ehab-d** [bitwarden/android#3826] opened 2024-08-24 18:24 UTC
### Bitwarden Beta

- [x] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Enable "Unlock with Biometrics"
2. Open Bitwarden

### Expected Result

The fingerprint and/or facial recognition popup should open.

### Actual Result

I have to click "Use biometrics to unlock" button everytime.

### Build Version

v2024.8.0 (18985)

### Environment Details

OPPO A15 - Android 10

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-08-24 19:22
Hello @Ehab-d,

Thank you for your report. I was able to reproduce this behaviour and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,

**Comment by djsmith85** [comment] 2024-08-25 07:38
Duplicate of #3724

**Comment by djsmith85** [comment] 2024-08-25 07:38
Hi there!

Thank you for your report, it seems like it is a duplicate of this one (#3724).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Comment by djsmith85** [comment] 2024-08-25 07:38
Hi there!

Thank you for your report, it seems like it is a duplicate of this one (#3724).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-08-25 07:38 UTC
Labels: bug
