### ISSUE TITLE
iOS not auto-filling properly with argon2id

### ISSUE THREAD

**Issue by BenjaminMichaelis** [bitwarden/android#2389] opened 2023-02-22 04:35 UTC
### Steps To Reproduce

1. Change to argon2id authentication. I tested with Kdf memory of 105mb as well as 90mb, and multiple iterations (5+) with parallelization of 1. These memory values are below the iOS auto fill memory limit (https://keepassium.com/articles/autofill-memory-limits/) which is why it surprises me it fails. Also there isn’t a warning of this limit as well both when setting, and when a failure occurs due to memory I would expect an error message. Even at 64mb, it doesn’t work consistently (sometimes takes multiple tries) even after flushing the memory.
2. try to auto fill for a normally working login on iOS device (I used a iPhone 13 Pro for testing). I tested on sites like google.com and Hulu
3. observe nothing being auto filled into the appropriate fields
4. Revert authentication back to PBKDF2 (even 2,000,000 iterations) and observe that auto fill works again

### Expected Result

Auto fill on iOS to work with memory limits up to 120mb

### Actual Result

Auto fill doesn’t work/actually fill in details. Tried on multiple site and apps, from safari to chrome to apps like Hulu. It works fairly consistently at 64mb and maybe higher but haven’t done more precise testing

### Additional Context

There isn’t a warning of the 120mb limit as well both when setting, and when a failure occurs due to memory I would expect an error message. But even at 64mb, it doesn’t work consistently (sometimes takes multiple tries) even after flushing the memory, before auto fill actually works.

### Operating System

iOS

### Operating System Version

16.3

### Device

iPhone 13 Pro

### Build Version

Version: 2023.2.0 (3044)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by SergeantConfused** [comment] 2023-02-23 18:34
Hi @BenjaminMichaelis,

This has been escalated for further investigation. If you have more information that can help us, please feel free to add it below. 


Thank you.

**Comment by BenjaminMichaelis** [comment] 2023-02-23 19:05
> Hi @BenjaminMichaelis,
> 
> 
> 
> This has been escalated for further investigation. If you have more information that can help us, please feel free to add it below. 
> 
> 
> 
> 
> 
> Thank you.

Here's a quick video on it. 

https://user-images.githubusercontent.com/22186029/220522587-bc0df238-96c3-4668-bec5-0e670c0efa3c.MOV

**Comment by frdrkolsson** [comment] 2023-03-06 10:52
Also experiencing this issue. 
iPhone 14 Pro on iOS 16.3.1 tried as low as 16mb, 3 iterations and 4 on parallelism without it working, not even on multiple tries.

https://user-images.githubusercontent.com/51903586/223090002-3e561787-4b24-4e6c-aa54-b6c13e691f3a.mov



Using the lowest possible settings, 16mb, 2 iterations, and 1 on parallelism works though. 
Hope this information helps.

**Comment by SergeantConfused** [comment] 2023-03-06 12:27
Hello @BenjaminMichaelis and @frdrkolsson,

Could you please activate Touch/Face ID as an unlocking method (https://bitwarden.com/help/biometrics/) and then attempt to perform Auto-Fill and let me know if you encounter the same behaviour? I ask because there are reports that indicate that this happens only when you unlock the client using the master password though the Auto-Fill flow.


Thank you in advance,

**Comment by mrrfv** [comment] 2023-03-06 14:25
@SergeantConfused I'm using Argon2id with very high KDF memory, and I can confirm that AutoFill works just fine when the vault is being unlocked via biometrics. The problem is that whilst I am able to use autofill using Touch/Face ID now, it didn't work previously for some reason - I was still being asked for the master password (which can't be verified due to the memory limits of iOS) to enable biometric unlocking through autofill despite it being active & working on the app itself.

**Comment by BenjaminMichaelis** [comment] 2023-03-08 03:27
> Hello @BenjaminMichaelis and @frdrkolsson,
> 
> Could you please activate Touch/Face ID as an unlocking method (https://bitwarden.com/help/biometrics/) and then attempt to perform Auto-Fill and let me know if you encounter the same behaviour? I ask because there are reports that indicate that this happens only when you unlock the client using the master password though the Auto-Fill flow.
> 
> Thank you in advance,

I do encounter the same issue (with a slight twist). It still doesn't autofill, but I get in a loop of biometric unlock pending verification of master password, entering in the master password, then it closing the autofill (the same action as when I finished entering in my pin when I was testing that). This was at a KDF memory of 90mb.

**Comment by frdrkolsson** [comment] 2023-03-13 07:57
> Hello @BenjaminMichaelis and @frdrkolsson,
> 
> Could you please activate Touch/Face ID as an unlocking method (https://bitwarden.com/help/biometrics/) and then attempt to perform Auto-Fill and let me know if you encounter the same behaviour? I ask because there are reports that indicate that this happens only when you unlock the client using the master password though the Auto-Fill flow.
> 
> Thank you in advance,

I have biometrics enabled (Face ID), and I've tried to disable/re-enable, without solving this matter. 
After biometrics passes, the dialog disappears, and nothing is filled, with a brief moment before the keyboard is back up and I can try again, without avail. I have not yet succeeded in any successful autofills with any decent settings.

Just to emphasize, with the following settings, it works every time, but anything above it fails. 
* 16mb
* 2 iterations
* 1 on parallelism.

**Comment by SergeantConfused** [comment] 2023-03-26 16:55
Thank you all for your assistance; We are looking into this matter internally at this stage.


I thank you in advance for your understanding and patience.

**Comment by quexten** [comment] 2023-03-29 17:03
In case it helps triaging @SergeantConfused this is an iOS autofill context limitation. It is well known on other password managers https://keepassium.com/articles/autofill-memory-limits/ . The "fix" is displaying a warning when trying to log in during autofill, with too high argon2 memory configuration, that explains the issue / warns about too low memory and possibly suggests to log in to the main app before autofilling (since there the limit does not apply).

**Comment by clemlesne** [comment] 2023-06-27 12:35
Issue solved for my side (1000 entries approx):

- Failing: Argon2id 256 MB
- Failing: Argon2id 128 MB
- Ok: Argon2id 64 MB

**Comment by arderyp** [comment] 2023-08-09 01:12
I'm having the same issue on latest iOS. I feel like it started happening somewhat recently, maybe ios 16.  Argon2 worked fine for a while.

I am using all the default argon 2 setting for memory, iterations, and parallelism

I get the warning often, but not every time.  Some times the auto fill works despite the warning, sometimes it doesn't

**Comment by arderyp** [comment] 2023-08-27 01:19
After more testing, whenever the auto populate fails for me, it always works on the second attempt following the same steps

Sometimes it works first time, sometimes it requires two tries

In every case, I see the KDF memory warning

**Comment by arderyp** [comment] 2023-09-21 16:19
This is still happening on the latest major release iOS 17.0

Same behavior: always shows memory warning; sometimes auto-fill works first time, else auto-fill always works on second attempt

**Comment by sallyFoster** [comment] 2023-09-21 21:07
It doesnt autofill when you need to input the master password. It just stays blank and does nothing.

**Comment by arderyp** [comment] 2023-09-21 21:26
@sallyFoster indont understand your comment.  The BitWarden master password should not be auto filled. You enter that manually and then BW returns you to the web/app login form and auto fills *that*

At least, it should auto fill that.  Sometimes it doesn't, which is what this issue is about

**Comment by sallyFoster** [comment] 2023-09-21 21:31
No, if you want extra security, you can have the master password to be required on your iPhone even with biometrics on. When you have the master password added on top of biometrics, it doesn't auto-fill ever.

**Comment by Gerardv514** [comment] 2023-09-23 13:23
@SergeantConfused this appears to be the same however I had never had this issue until updating bitwarden to 2023.9. Previously I had been on iOS 16, no issues with previous versions of BW. I then updated iPhone 14 pro to iOS 17 and then a security update for that came out and all was good. Bitwarden app version 2023.9 came out and now I’m receiving warning unlocking may fail due to insufficient memory. Clicking continue does not auto fill. I am using the default values for argon2.

**Comment by dickaux** [comment] 2023-09-25 02:03
Started with BW 2023.9.1.  IOS 15.7.9 on 256 gb iphone 7 plus.  had been using Argon2id for many months without trouble.

**Comment by BenjaminMichaelis** [comment] 2023-09-25 06:34
> Started with BW 2023.9.1.  IOS 15.7.9 on 256 gb iphone 7 plus.  had been using Argon2id for many months without trouble.
> 
> 

I also have begun having trouble with autofill when I hadn't previously in months (other than one off cases, but trying autofill a second time always worked). Now it fails no matter how many times I try. Have ended up having to open the app itself and copy over details. 

Using iOS 17.0 and Bitwarden Version: 2023.9.1 (4890)

**Comment by dickaux** [comment] 2023-09-25 14:16
Bitwarden support just emailed me:

I believe this is a known bug with Argon2: https://github.com/bitwarden/mobile/issues/2389
​
The workaround for the time being is to revert to ​pbkdf2 until the issue has been resolved.
​

**Comment by SergeantConfused** [comment] 2023-09-25 15:12
Hello,

@Gerardv514, @BenjaminMichaelis, @dickaux, have you had your (Vault Timeout) set to (Never) all this time, and this behaviour started only recently with version 2023.9.1?


Thank you in advance,

**Comment by dickaux** [comment] 2023-09-25 16:25
I get vault lock all the time. It doesn’t matter where Timeout is set.
Note that after each change in timeout, I log out and then restart entering
my master pw.
-Dickaux

**Comment by SergeantConfused** [comment] 2023-09-25 17:32
Hi @dickaux,

I understand that, and that is related to this (https://github.com/bitwarden/mobile/issues/2787); Regardless, have you had your Vault Timeout set to Never prior?


Thank you in advance,

**Comment by dickaux** [comment] 2023-09-25 17:54
Yes.  It was set to never when I first hit the bug.

-Dickaux

**Comment by arderyp** [comment] 2023-09-25 17:57
I don't *think* I've ever had vault timeout set to never, and I have this issue.  I didn't have it when I first enabled argon2 shortly after it became available, but it has been happening for a number of months and isn't a brand new issue for me

**Comment by BenjaminMichaelis** [comment] 2023-09-25 21:28
> Hello,
> 
> 
> 
> @Gerardv514, @BenjaminMichaelis, @dickaux, have you had your (Vault Timeout) set to (Never) all this time, and this behaviour started only recently with version 2023.9.1?
> 
> 
> 
> 
> 
> Thank you in advance,

Mine has been set to 15 minutes the whole time, for probably more than 6 months now.

**Comment by sallyFoster** [comment] 2023-09-26 00:50
Were you able to look into my issue because it still doesn’t work for me?

https://github.com/bitwarden/mobile/issues/2389#issuecomment-1730330344

**Comment by SergeantConfused** [comment] 2023-10-02 12:34
Hello everyone,

First, please read this (https://github.com/bitwarden/mobile/issues/2389#issuecomment-1488976242) for context. Some of you are only now encountering this matter because you did not need to unlock the client through the Auto-Fill flow (when performing Auto-Fill) up till the latest version (2023.9.1), and now you are asked to do so because of this (https://github.com/bitwarden/mobile/issues/2787).

1. The new warning message ''Unlocking may fail due to insufficient memory.'' would be shown on iOS at each and every unlocking attempt, such as through the Auto-Fill flow or when creating a new Send via the Share sheet, when the Argon2id Memory is set to 48 MB or higher and you are unlocking using the master password or PIN. It would not be shown when unlocking the main iOS client (the Bitwarden icon on the home screen).
2. If you are using Argon2id and you attempt to perform Auto-Fill and nothing happens after you enter the PIN or master password, meaning no credentials are entered into the webpage or you are stuck with a red message stating ''Biometric unlock disabled pending verification of master password'', your Argon2id KDF configuration is probably too high for the device you are using; Please revert to the default Argon2id values and set the KDF Memory to 45 MB and try again. If this behaviour continues, please get in touch with us (https://bitwarden.com/help/) so we'll have a look, and please include a link to this GitHub thread in your message.
3. If you are using Argon2id and you see the new warning message but are still able to perform Auto-Fill successfully, you can safely ignore that message; Alternatively, you can use Touch ID or Face ID to unlock your client and the warning message would not be shown in that case.
4. If you would like to use Argon2id with high KDF settings, possibly the same ones you had before you started needing to unlock your client at each Auto-Fill action, you can follow the workaround below. To be clear, when unlocking the iOS client using the master password or PIN, high KDF settings such as KDF Memory above 48 MB can result in the Auto-Fill action failing as mentioned in this GitHub thread; However, it may be possible to unlock the client via Touch ID or Face ID with those high KDF settings and perform Auto-Fill successfully.
A. Set the KDF Settings to Argon2id where (Iterations = 2) and (Memory = 16).
B. Log in via the Bitwarden iOS client.
C. Activate (Unlock with biometrics).
D. Open a browser, such as Safari, and perform Auto-Fill and enter your Bitwarden master password.
E. Attempt to perform Auto-Fill again to confirm that there no longer is a need to enter the master password during Auto-Fill, and that Touch ID or Face ID can be used instead.
F. Navigate back to Web Vault and change the KDF settings to the desired configuration.
G. Log in via the Bitwarden iOS client anew.

If you are encountering something different, please get in touch with us (https://bitwarden.com/help/) so we'd assist with your particular case, so that we'd keep this GitHub thread focused on this matter only.

I hope you find this clear and helpful, and I thank you in advance for your understanding and patience,

**Comment by arderyp** [comment] 2023-10-05 22:42
@SergeantConfused, regarding the comment you referenced at the top of your latest comment... does this mean this issue is with iOS AutoFill, and not with BitWarden Mobile?

> Some of you are only now encountering this matter because you did not need to unlock the client through the Auto-Fill flow (when performing Auto-Fill) up till the latest version (2023.9.1), and now you are asked to do so because of this (#2787).

I've read this a few times and can't make sense of the words.  I used to not experience this issue after enabling Argon2 shortly after BW made it available.  Then, at some point, I started receiving this warning frequently--sometimes the auto-fill would work regardless and, if not, it would always work on the second try. Now., since moving to ios17, the warning happens every time (still), and the first auto-fill attempt always fails, and the second attempt always works. **at no point during my history of argon2 usage have I changed my approach to using it in the UI... I've always used the ios auto-fill widget**. I mention this because the quoted bit above makes it sounds like this is user error due to changed behavior, but maybe I'm misreading your statement?

> 2. ... your Argon2id KDF configuration is probably too high for the device you are using; Please revert to the default Argon2id values and set the KDF Memory to 45 MB and try again. If this behavior continues, please get in touch with us (https://bitwarden.com/help/) so we'll have a look, and please include a link to this GitHub thread in your message.

I was using the default argon2 config provided by BitWarden. This set memory=64kb, iterations=3, parallelism=4.  I have changed memory to 48 as you suggested. **This resolved the issue for me**.

For those of us like myself who are not well versed in cryptography, does changing the memory setting in this way impact the security/strength of my vault?  Thanks very much for your helpful and thorough comment!

**Comment by quexten** [comment] 2023-10-06 01:49
>  I used to not experience this issue after enabling Argon2 shortly after BW made it available.

The dialog was only added later. In the initial argon2 release, there was no warning so if the app did not fit into the iOS memory constrained autofill environment, it would just crash. However, it also meant that it worked fine for 64MiB (the default) in most cases.

The warning triggers at at 48 MiB (lower than the 64 MiB default), regardless of whether the app would actually crash. It might make sense to just adjust the default argon2 values down (maybe increasing iterations to compensate) just so that users don't run into this as often.

> For those of us like myself who are not well versed in cryptography, does changing the memory setting in this way impact the security/strength of my vault? Thanks very much for your helpful and thorough comment!

As long as you have a good master password, no. Even if not, the difference between 48 MiB and 64 MiB, for cracking purposes, is not that relevant. It nearly linearly scales in this case, meaning that cracking your vault - should someone have an encrypted offline copy of it - is about 33% faster on the lower memory setting. You can compensate by increasing iterations (to 4), if you really feel that it is necessary. Either way, at both settings cracking any medium to high complexity passwords is not possible for a reasonable amount of time/money investment.

**Comment by arderyp** [comment] 2023-10-06 02:31
Thanks @quexten! Seeing as I'm on a modern iPhone with strong hardware, I'm surprised the 64m setting triggers errors on my phone, while also triggering errors on older models.  I guess iOS doesn't care about the hardware capability and those the error in all cases, which seems dumb.  Again, maybe I'm misunderstanding. Anyways, thanks again.

**Comment by quexten** [comment] 2023-10-06 02:42
> Thanks @quexten! Seeing as I'm on a modern iPhone with strong hardware, I'm surprised the 64m setting triggers errors on my phone, while also triggering errors on older models. I guess iOS doesn't care about the hardware capability and those the error in all cases, which seems dumb. Again, maybe I'm misunderstanding. Anyways, thanks again.

Yeah, the hardware is certainly not the limit. It's just an iOS software limitation specifically within autofill contexts. When unlocking in the app, even 1GiB (the max setting) works fine on iOS.

**Comment by Gerardv514** [comment] 2023-10-06 13:07
> > Thanks @quexten! Seeing as I'm on a modern iPhone with strong hardware, I'm surprised the 64m setting triggers errors on my phone, while also triggering errors on older models. I guess iOS doesn't care about the hardware capability and those the error in all cases, which seems dumb. Again, maybe I'm misunderstanding. Anyways, thanks again.
> 
> Yeah, the hardware is certainly not the limit. It's just an iOS software limitation specifically within autofill contexts. When unlocking in the app, even 1GiB (the max setting) works fine on iOS.

Is there a way to get this information out to Apple? I would assume companies have access to other companies to work together when issues cross the boundary lines. Surely there has to be a way to suggest to Apple to increase the limitation within the software.

**Comment by quexten** [comment] 2023-10-06 22:18
A solution would be to decouple the KDF used for local unlocking from the account KDF. Usually, a KDF is adjusted for the device it is run on. With the account's KDF this is not possible as it is used on multiple devices. But the locally encrypted user symmetric key could be encrypted instead with a KDF adjusted to the device (i.e 48MiB on iOS, iterations automatically calibrated to take ~1 second). This would (slightly) increase the security for all users, and make it so that any account KDF setting is safe.

**Comment by arderyp** [comment] 2023-10-07 00:28
> Yeah, the hardware is certainly not the limit. It's just an iOS software limitation specifically within autofill contexts. When unlocking in the app, even 1GiB (the max setting) works fine on iOS.

@quexten can you clarify this comment?  Does this include:

1. Hit auth page in browser
2. Move to BW app
3. Unlock vault in BW app
4. Move back to browser
5. Use autofill functionality

Will this get around the error, even with higher memory setting? I get the error when I go from step 1 straight to step 5. Are steps 2-3 a workaround? Or when you say "unlocking in the app" do you just mean unlocking the vault from the BW app and using copy/paste to move username and password into the browser auth form?

**Comment by sallyFoster** [comment] 2023-10-14 23:07
> Hello everyone,
> 
> First, please read this ([#2389 (comment)](https://github.com/bitwarden/mobile/issues/2389#issuecomment-1488976242)) for context. Some of you are only now encountering this matter because you did not need to unlock the client through the Auto-Fill flow (when performing Auto-Fill) up till the latest version (2023.9.1), and now you are asked to do so because of this (#2787).
> 
>     1. The new warning message ''Unlocking may fail due to insufficient memory.'' would be shown on iOS at each and every unlocking attempt, such as through the Auto-Fill flow or when creating a new Send via the Share sheet, when the Argon2id Memory is set to 48 MB or higher and you are unlocking using the master password or PIN. It would not be shown when unlocking the main iOS client (the Bitwarden icon on the home screen).
> 
>     2. If you are using Argon2id and you attempt to perform Auto-Fill and nothing happens after you enter the PIN or master password, meaning no credentials are entered into the webpage or you are stuck with a red message stating ''Biometric unlock disabled pending verification of master password'', your Argon2id KDF configuration is probably too high for the device you are using; Please revert to the default Argon2id values and set the KDF Memory to 45 MB and try again. If this behaviour continues, please get in touch with us (https://bitwarden.com/help/) so we'll have a look, and please include a link to this GitHub thread in your message.
> 
>     3. If you are using Argon2id and you see the new warning message but are still able to perform Auto-Fill successfully, you can safely ignore that message; Alternatively, you can use Touch ID or Face ID to unlock your client and the warning message would not be shown in that case.
> 
>     4. If you would like to use Argon2id with high KDF settings, possibly the same ones you had before you started needing to unlock your client at each Auto-Fill action, you can follow the workaround below. To be clear, when unlocking the iOS client using the master password or PIN, high KDF settings such as KDF Memory above 48 MB can result in the Auto-Fill action failing as mentioned in this GitHub thread; However, it may be possible to unlock the client via Touch ID or Face ID with those high KDF settings and perform Auto-Fill successfully.
>        A. Set the KDF Settings to Argon2id where (Iterations = 2) and (Memory = 16).
>        B. Log in via the Bitwarden iOS client.
>        C. Activate (Unlock with biometrics).
>        D. Open a browser, such as Safari, and perform Auto-Fill and enter your Bitwarden master password.
>        E. Attempt to perform Auto-Fill again to confirm that there no longer is a need to enter the master password during Auto-Fill, and that Touch ID or Face ID can be used instead.
>        F. Navigate back to Web Vault and change the KDF settings to the desired configuration.
>        G. Log in via the Bitwarden iOS client anew.
> 
> 
> If you are encountering something different, please get in touch with us (https://bitwarden.com/help/) so we'd assist with your particular case, so that we'd keep this GitHub thread focused on this matter only.
> 
> I hope you find this clear and helpful, and I thank you in advance for your understanding and patience,

Setting the KDF memory to 48 MB in iOS fixed it for me. However, the default value for the  KDF memory that BitWarden sets is 64 MB. Is 48 MB not a secure enough memory value?

**Comment by arderyp** [comment] 2024-05-17 21:54
@TheNightRider12... with what KDF memory setting?

**Comment by arderyp** [comment] 2024-05-18 22:27
The autofill worked for me changing to 64/4/4, but iOS still gives me a warning about KDF memory. It may actually be a new warning, but it happens nonetheless.  But the autofill now works in first attempt whereas before it was always requiring two attempts.

**Comment by arderyp** [comment] 2024-05-22 15:56
Now it's requiring 2 attempts to autofill. So the issue is, for me, the same as it's ever been, despite report above. I am running latest iOS and BW

**Comment by vvolkgang** [comment] 2024-06-20 19:31
Issue migrated to https://github.com/bitwarden/mobile/issues/2389

**Closed by vvolkgang** 2024-06-20 19:31 UTC
Labels: bug
