### ISSUE TITLE
Unable to process your request

### ISSUE THREAD

**Issue by ulyssesdotcodes** [bitwarden/android#3746] opened 2024-08-15 14:28 UTC
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open app
2. Try logging in

### Expected Result

Can log in

### Actual Result

Error saying "we were unable to process your request. Pease try again or contact us"

### Additional Context

Started happening as soon as the app updated to the new UI. The server is a bitwardenrs docker that is fully updated. Accessing the vault through the web works fine.

Was in the beta, tried dropping out of the beta and reinstalling, but same issue.

### Build Version

2024.7.1 (I think?)

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by thibaultmol** [comment] 2024-09-01 22:39
Having this same issue, even when i switch to the regular version and clear the storage on my phone 
(my homesever is vaultwarden technically though)

**Comment by SergeantConfused** [comment] 2024-09-07 13:48
Hello everyone,

1. Are you still able to reproduce this behaviour in more recently versions of vaultwarden (bitwarden_rs)?
2. @ulyssesdotcodes, did you raise this in the vaultwarden (bitwarden_rs) [repository](https://github.com/dani-garcia/vaultwarden/issues?q=is%3Aissue+unable+to+process+your+request)?

Thank you in advance,

**Comment by thibaultmol** [comment] 2024-09-07 15:08
I personally reinstalled the app again (cleared the storage first) 
I did it before and didn't fix it. but doing it a second time did fix it.... i don't know why
Just cause, here are the versions of things:
Bitwarden app: 2024.7.1 (11086)
android: 13, fairphone 5
Vaultwarden: 1.30.1 (needs an update, i know)

**Comment by ulyssesdotcodes** [comment] 2024-09-07 15:35
I switched to the non-beta version and that fixed it. The docker was up to date when I first had the issue - hesitant to reinstall the beta version now that it's working

**Comment by SlimGary** [comment] 2024-09-16 04:21
Same issue here on the beta version and vaultwarden self-hosted server. Even trying to get my password hints brings the error.

**Comment by SergeantConfused** [comment] 2024-09-16 13:43
Hello everyone,

Thank you all for your input. I highly recommend checking out the link in my prior response, and seeing if you can find more information about this in vaultwarden's GitHub repository. I will now close this GitHub report as I am unable to reproduce this behaviour, and it seems like it's unique environments based on vaultwarden.

All the best,

**Closed by SergeantConfused** 2024-09-16 13:43 UTC
Labels: bug

**Comment by RokeJulianLockhart** [comment] 2024-10-02 12:07
Just had this occur using https://play.google.com/store/apps/details?id=com.x8bit.bitwarden on my Fairphone 5.

**Comment by NexGen-3D-Printing** [comment] 2025-01-17 23:27
Still an issue today, my app updated from an old version and I got this error, had to remove it and install version 2024.6, and now it works again, I will stay on this version until the heat death of the known universe, anymore issues and I will probably just go back to old school with a text file in a password encrypted zip file as its far far more reliable, less convenient but more reliable.
