### ISSUE TITLE
Passkeys regression - doesn't work when you try to authenticate with locked vault 

### ISSUE THREAD

**Issue by raywdude** [bitwarden/android#4385] opened 2024-11-25 16:15 UTC
### Steps To Reproduce

1. Open Bitwarden
2. Make sure passkeys are enabled
3. Open your browser of choice
4. Open recent apps menu and swipe away the Bitwarden app
5. Go to a passkey supported site and try to login using passkey
6. Authenticate using biometrics 

### Expected Result

Authentication is successful

### Actual Result

Bitwarden throws an error "passkey authentication failed because user could not be verified"

### Build Version

2024.11.6

### What server are you connecting to?

US

### Environment Details

Samsung s24 ultra (sm-s928u1)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by singhh9596** [comment] 2024-11-26 14:38
Yes, this is happening on the latest beta build available on github. I reinstalled the app from fdroid and now it's working fine.

**Comment by raywdude** [comment] 2024-11-26 14:44
It's the latest play store release, 11.6.

**Comment by singhh9596** [comment] 2024-11-26 14:52
> It's the latest play store release, 11.6.

Version 2024.11.3. install this version for the passkey or wait for the dev team to release an update with fix

**Comment by cbbit** [comment] 2024-11-26 21:53
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/android/issues/4239

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by cbbit** 2024-11-26 21:53 UTC
Labels: bug
