### ISSUE TITLE
using a space at the beginning of otpauth:// generate a wrong OTP

### ISSUE THREAD

**Issue by AnthillSudoku** [bitwarden/android#2122] opened 2022-10-10 18:10 UTC
### Steps To Reproduce

Bitwarden Android, web interface and Firefox's extension are affected

1. Open Bitwarden
2. clone a working entry that has a valid OTP
3. edit the cloned entry putting a space at the beginning of otpauth://... like this:
" otpauth://..."
5. save

### Expected Result

two possible results:

1. a space before otpauth:// is wrong, bitwarden should not generate any OTP but display a warning on the wrong OTP field
2. bitwarden deals with wrong characters like spaces before otpauth:// and generate a working OTP

### Actual Result

a wrong OTP is generated

### Additional Context

I found it while copying and pasting the otpauth:// line. Bitwarden interface's extension is small and it's not easy to immediately find what is wrong

### Operating System

Android

### Operating System Version

10

### Build Version

2022.9.1 (5047)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by tangowithfoxtrot** [comment] 2022-12-21 22:20
Thanks, @luca-e075e!

I've confirmed the behavior and marked this as being reproducible internally.

**Comment by jayg2309** [comment] 2023-09-26 21:18
Is someone working on this?
Can i work on this?

**Comment by djsmith85** [comment] 2023-09-26 21:48
@jayg2309 Thank you for your interest in contributing.

As a starting guide please have a look at our [Contribution Guidelines](https://contributing.bitwarden.com/). These will get you started with setting up your development environment and how to proceed with your contribution.

Please reference this issue when you create a pull request.

**Comment by jayg2309** [comment] 2023-09-26 22:33
Okay thankyou

**Comment by flooxo** [comment] 2023-10-24 16:34
Is this sill an open issue? I was not able to reproduce it, as the new OTP is generated correctly after adding a space. Otherwise I am happy to help solve the issue :)

**Comment by FlorianLang06** [comment] 2023-11-08 17:55
I tested it on my iPhone and in the Chrome extension. In Both cases the issue is still happening. It is important that its an OTP that begins with otpauth://. @flooxo if you want to fix it, feel free to do that or I try to do this.

**Comment by FlorianLang06** [comment] 2023-11-09 09:39
I will wait some days and if you don't respond to this, I will fix this issue. I already know how to fix this, but if you want to fix it, I let you fix this.

**Comment by flooxo** [comment] 2023-11-09 10:08
OK, thanks for the note. Feel free to fix it if you already know where in the code :)

**Comment by FlorianLang06** [comment] 2023-11-09 10:15
Ok, but I have to get the project up and running first on my PC.

**Comment by flooxo** [comment] 2023-11-09 10:18
If you give me a hint where in the code something should be changed, I can do it too. Whatever suits you best :)

**Comment by FlorianLang06** [comment] 2023-11-09 10:28
I try if the setup on my PC is easy, if it isn't easy I give you a hint so you can do it

**Comment by FlorianLang06** [comment] 2023-11-09 10:41
@flooxo Do you think its a good idea to remove the space at saving and at generation. At generating for existing entries and saving for new entries.

**Comment by flooxo** [comment] 2023-11-09 11:21
Yeah, I guess the expected behavior when cloning an entry with an otp is to still have a valid otp path, right? So I would suggest to just trim the whitespaces

**Comment by FlorianLang06** [comment] 2023-11-09 18:20
I can't get xamarin running. @flooxo you can solve this issue. In this method the key must be trimmed because the StartwWith check don't work https://github.com/bitwarden/mobile/blob/793c5fef6f64b3c75b801874750d5ac26bcd5a9f/src/Core/Services/TotpService.cs#L9

You can also search for the code where a entry get saved and trim the string before saving

**Comment by flooxo** [comment] 2023-11-09 18:41
Ok, thanks, I've already looked at that method. I'll have to take a closer look at where the key is saved, because wouldn't it be a better solution if it was already saved correctly beforehand?

**Comment by FlorianLang06** [comment] 2023-11-09 19:00
Yes, but I think trim it at the generation is also necessary for keys which are already stored wrong.

**Comment by FlorianLang06** [comment] 2023-11-12 16:33
@flooxo would you also try to fix this in the browser extensions? If not I can try it. 

I think it's a good idea to create an new issue there and attach the link of this issue, so anyone has the context to the issue.

**Comment by flooxo** [comment] 2023-11-12 20:55
Sure, i'll give it a try. Thanks :)

**Comment by vvolkgang** [comment] 2024-06-20 19:34
Issue migrated to https://github.com/bitwarden/mobile/issues/2122

**Closed by vvolkgang** 2024-06-20 19:34 UTC
Labels: bug, good first issue
