### ISSUE TITLE
Android Sorting Of Similar Entry Names Is Dependent Upon Whether A Username Also Exists

### ISSUE THREAD

**Issue by 48crash** [bitwarden/android#4395] opened 2024-11-28 19:59 UTC
### Steps To Reproduce

In the Bitwarden Android 2024.10.0 (11270) app:

1. Create several sets of vault items that have similar but different _Names_
2. Add _Usernames_ to some of the items
3. Make sure that these items are in the same folder

### Expected Result

The sort order of the vault items with similar but different _Names_ should be alphabetical based upon the _Name_ regardless of whether there is a _Username_. This is the current behavior in the iOS app and on the Bitwarden website.

### Actual Result

The Android sort logic is is not immediately obvious but it is not always alphabetical when _Usernames_ exist.

### Screenshots or Videos

Android Screenshots

![Android_1](https://github.com/user-attachments/assets/5c45723d-b1df-4dff-968c-8c707fca5f15)
![Android_2](https://github.com/user-attachments/assets/1fc438e7-e9ba-4e35-9e8c-aacf81953ce4)

iOS Screenshots (same data)

![iOS_1](https://github.com/user-attachments/assets/cba3f3b1-928f-4819-9d73-997765348c56)
![iOS_2](https://github.com/user-attachments/assets/57dfbc53-f5e7-4fdc-b03a-90da0b06229a)

Website Screenshot (same data)

![Web Browser](https://github.com/user-attachments/assets/64106e1f-64da-4789-b078-ed1742d69a9f)

### Build Version

Android 2024.10.0 (11270) and iOS 2024.11.0 (1680)

### What server are you connecting to?

US

### Environment Details

Pixel 8a running Android 15 and iPhone 15 Pro running iOS 18.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment] 2024-11-29 07:40
Hi there,

Thank you for your report! 

I was able to reproduce this issue with version 2024.10.0. 

I also tested this using our latest stable release, version 2024.11.5, and was not able to reproduce this behavior in that version of the application. The login items were sorted in alphabetical order based on the name of the item, and the presence of a username in one of those items did not change this.

Version 2024.11.5 is currently in a staged roll-out, which is why you may not have received it yet. You can attempt to reinstall the Bitwarden application from the Google Play Store or you can download this from our release page: https://github.com/bitwarden/android/releases

Thanks once again for taking the time to report this to us!

I will be closing this issue out as the behavior reported is already addressed in future build.

**Closed by rmcdowell-bitwarden** 2024-11-29 07:40 UTC
Labels: bug
