### ISSUE TITLE
Biometric authentication not promoting automatically 

### ISSUE THREAD

**Issue by Ironfist69** [bitwarden/android#3741] opened 2024-08-15 05:58 UTC
### Bitwarden Beta

- [ ] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Try to autofill or open Bitwarden app
2. If you have set biometric it will not prompt you for Biometric authentication, you have to manually click on that button.

### Expected Result

Like the previous app, Biometric authentication prompt should automatically appear 

### Actual Result

Not promoting automatically for biometric authentication.

### Screenshots or Videos

https://github.com/user-attachments/assets/39354f02-c13e-4ae4-a823-1c3c769fa4df

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.8.0 (18985)

### Environment Details

SM-A135F
Android 14
OneUI 6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment] 2024-08-15 06:15
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/android/issues/3724 .

This issue will now be closed.

Thanks!

**Closed by daniellbw** 2024-08-15 06:15 UTC
Labels: bug
