### ISSUE TITLE
View password missing special character

### ISSUE THREAD

**Issue by alexwilczewski** [bitwarden/android#4281] opened 2024-11-11 16:11 UTC
### Steps To Reproduce

1. Create a login with password that contains the character "<".
2. View the newly created login.
3. Click the unhide button for the password.

### Expected Result

The password will show the "<" special character.

### Actual Result

The password does not show the "<" special character.

### Screenshots or Videos

The actual password (seen from the edit screen)
![Screenshot_20241111-090605](https://github.com/user-attachments/assets/3f171a3b-bad1-4fb7-bb74-c95fe8df7883)

The viewed password
![Screenshot_20241111-090600](https://github.com/user-attachments/assets/d8960310-0fb6-4a7e-96c0-f6b9bfb0afca)

### Build Version

2024.10.0

### What server are you connecting to?

US

### Environment Details

- Device: Pixel 8

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-11-11 16:35
Hi there!

Thank you for your report, it seems like it is a duplicate of https://github.com/bitwarden/mobile/issues/3110

The screenshots you provided indicate this issue being on the old Android apps and should be resolved on the new native Android app.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-11-11 16:35 UTC
Labels: bug
