### ISSUE TITLE
Can't press top bar buttons in portrait mode

### ISSUE THREAD

**Issue by rharish101** [bitwarden/android#1899] opened 2022-05-03 18:20 UTC
### Steps To Reproduce

1. Open the app
2. Click on any button in the top bar
3. Observe that nothing happens
4. Rotate the phone to get it into landscape mode
5. Do step 2
6. Observe that it works as expected 

### Expected Result

Button presses should work irrespective of the orientation

### Actual Result

Button presses in the top bar don't work in portrait mode

### Screenshots or Videos

Bitwarden doesn't allow taking screenshots/videos, so I can't add anything here.

### Operating System

Android

### Operating System Version

10

### Device

Xiaomi POCO F1

### Build Version

12.0.3.0 MIUI

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Bantul-the-great** [comment] 2022-05-08 16:45
I am also facing the same issue with my Redmi note 7s(lavender) running Android 10, MIUI GLOBAL 12.5.1 STABLE......
Bitwarden version- 2.18.0....

**Comment by PolarNelvana** [comment] 2022-05-10 05:27
I am also having the same problem with Android. Super annoying.

**Comment by Bantul-the-great** [comment] 2022-05-11 16:08
The 

> I am also facing the same issue with my Redmi note 7s(lavender) running Android 10, MIUI GLOBAL 12.5.1 STABLE...... Bitwarden version- 2.18.0....

The issue is solved by the time now. No new updates of the app was pushed but yet it got fixed. I don't know how. Anyway that's good now. Thank you...

**Comment by rharish101** [comment] 2022-05-11 16:16
FYI I still have the same issue.

**Comment by asen23** [comment] 2022-05-12 01:31
I have the same issue, i think caused by fullscreen mode. I found other workaround other than using landscape mode by opening another app and use split app so bitwarden is on bottom, in that mode the top bar work again.

**Comment by kingosticks** [comment] 2022-05-23 22:37
I have this issue and have resorted to turning the phone landscape to use these top buttons. It's very annoying, thanks MIUI.  Whatever this bug is, it's not limited to bitwarden. I also have the same issue in the official GitHub app and a banking app.

**Comment by rharish101** [comment] 2022-07-15 06:27
Now even landscape mode doesn't work for me! The only workaround for me is what @asen23 suggested. I'm currently using version 2022.6.1.

**Comment by rharish101** [comment] 2022-07-15 06:46
I found out that the cause of this issue was hiding the notch without moving the status bar. Either keeping the notch, or hiding the notch while moving the status bar solved this.

However, I'm still keeping this issue open, since Bitwarden should work irrespective of my notch settings.

**Comment by PolarNelvana** [comment] 2022-07-15 12:43
> I found out that the cause of this issue was hiding the notch without moving the status bar. Either keeping the notch, or hiding the notch while moving the status bar solved this.
> 
> However, I'm still keeping this issue open, since Bitwarden should work irrespective of my notch settings.

I don't have a notch on my phone but I still have the problem. Using Galaxy s8+.

**Comment by Marc2076** [comment] 2022-08-07 18:23
Same issue for me with Xiaomi Mi 8.
It works in landscape mode (thanks for the tip).
The notch config for Bitwarden app in "Auto" or in "Always show notch" doesn't help.
Beeing in fullscreen or not doesn't help.

**Comment by hdinhsg** [comment] 2022-08-19 04:28
Same here on my Mi 8 EE. Workaround is to use landscape mode (thanks to @asen23) or hide the notch completely.
Hope this will be fixed soon.

**Comment by delmicio** [comment] 2022-11-04 21:32
MIUI Global 12.0.10 here with Xiomi Mi 9 lite device. I can confirm this. 

> I found out that the cause of this issue was hiding the notch without moving the status bar. Either keeping the notch, or hiding the notch while moving the status bar solved this.
> 
> However, I'm still keeping this issue open, since Bitwarden should work irrespective of my notch settings.

**Comment by savvdm** [comment] 2023-01-09 12:35
I had the similar issue on MIUI Global 12.0.4 (Redmi 9). I observed the same behavior with other apps as well, e.g. with this one: https://play.google.com/store/apps/details?id=com.kunzisoft.keepass.free&hl=en&gl=US
I assume this is more of a MIUI problem, although it took me some time to find this out. Once I learned this, I just turned off notch hiding - this is not a problem for me.

**Comment by sivann** [comment] 2023-04-27 14:03
Still an issue, Mi9. Work only in landscape, or in split screen if it's the bottom window.

**Comment by SergeantConfused** [comment] 2024-05-05 17:25
Hello everyone,

Has anyone encountered this behaviour in version 2024.4.0 or newer?


Thank you,

**Comment by Marc2076** [comment] 2024-05-05 19:51
Hello,
I can still reproduce the issue with version 2024.4.0 (10172).
Regards,

**Comment by vvolkgang** [comment] 2024-06-20 20:01
Issue migrated to https://github.com/bitwarden/mobile/issues/1899

**Closed by vvolkgang** 2024-06-20 20:01 UTC
Labels: bug
