### ISSUE TITLE
Match detection "Host" not working

### ISSUE THREAD

**Issue by larena1** [bitwarden/android#3341] opened 2024-06-23 21:16 UTC
### Steps To Reproduce

1. Create entry with URL https://example.com and match detection "Host"
2. Navigate to example.com in Chrome
3. Check native autofill 

### Expected Result

Entry should be suggested

### Actual Result

No suggestions 

### Build Version

Native beta 2024.06.00

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-06-24 05:22
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by otaconix** [comment] 2024-07-06 21:58
I'm running into the same issue. What's interesting is that, when I manually lookup the entry I want through the auto-fill flow and tell Bitwarden to "Auto-fill and save", the URL added to the item is exactly the same as another one that was already there.

I haven't grokked the code I've been looking at entirely, but it looks like @larena1's analysis is right on the money. Most URLs are unlikely to contain an explicit port, as they tend to use the implicit default (80 for HTTP and 443 for HTTPS).

If there's anything I can do to help debug this further, let me know!

**Comment by libreom** [comment] 2024-07-10 14:01
Brave browser autofill on most websites is not working(works on some very few site)

**Comment by kaishi961125** [comment] 2024-07-14 07:04
I have the same situation. host mode doesn't work.

**Comment by uniquePWD** [comment] 2024-07-14 07:56
For the record, 

It's even matching the full URL. I have my default set to host and its trying to match `http://localdomain.tld/subdir`

**Comment by SheilaMacKay86** [comment] 2024-07-21 00:59
Do nor try downloading those spy apps because you will see nothing from spy apps i tried so many spy apps and all give me nothing, so I saw reviews from other customers recommending hackerspytech @ gmail com o I have no option and I messaged them on mail their response was fast and i told them all I need from my spouse phone. Finally now I can easily see all my spouse messages, and deleted messages, call’s records and history I also have access to my spouse phone messages and also from all social media, i never knew there’re still a hacker like hackerspytech, I also recommend their service and I will always do, if you need help on how get into your spouse phone then message them

**Comment by nairol203** [comment] 2024-07-22 04:54
+1
same issue for me with host mode

**Comment by uniquePWD** [comment] 2024-07-24 22:16
Well #3611 certainly improves the user experience. But it should match the port.

**Comment by Safemode** [comment] 2024-08-02 17:35
Also running into this same problem, thought I was going crazy. I have default URI Match Detection set to Host, I go to my internal IP:port, and it doesn't find it. The same issue occurs on the beta app too. If I open up the Autofill and choose to "Add an Item", the URI only has the IP without the port on there.

**Comment by uniquePWD** [comment] 2024-08-07 15:33
Using the beta, it was overly greedy for a few days, but now that #3623 landed, it's broken again. I'm unsure which tests this passed as it can't have been a functionality test. 

@david-livefront did you test this manually at all?

**Comment by uniquePWD** [comment] 2024-08-08 15:18
pinging @david-livefront did you test the now host matching manually at all?

**Comment by uniquePWD** [comment] 2024-08-12 17:33
Afternoon @david-livefront still trying to get information as to what your experience was

**Comment by uniquePWD** [comment] 2024-08-14 16:27
I understand that there's a lot of noise that's inevitably neccessary to blank out in order to maintain productivity. But surely keep an eye on things that you're working on. Especially when you land something. In this case, the landing actually caused a regression. Being able to juggle work and keep an eye on the bug tracker is part and parcel of development. It's harder when it's open source and I get that too. But the whole point of a public beta is that it enables us to catch things early and for the developers to react in an agile manner. We are all trying to work towards the best BitWarden release ever. Let's make that happen together.

**Comment by vvolkgang** [comment] 2024-09-17 15:20
👋🏾 I meant to share an updated earlier but dropped the ball, for which I'm sorry. During our research we concluded that the Autofill Framework isn't sending us the port as expected. While we'll continue to monitor how to provide this functionality, based on your feedback we'll discuss reverting the recent changes and how that will impact other areas of the product. 

Thank you for your feedback and patience 🙏🏾

**Closed** 2024-10-15 14:21 UTC
Labels: bug

**Comment by uniquePWD** [comment] 2024-11-04 07:21
So the attempted fix finally made it to release, though it skipped beta. It's now matching domain properly, but not host (port). Is anyone actually testing things?

**Comment by Safemode** [comment] 2024-11-04 14:17
I can also confirm from my testing on the recently released 2024.11.0 version, that while the Default URI Match Detection is set to Host, it matches the domain/IP, but does not match the port, and I'm seeing all entries for that domain/IP in the auto-fill shortcut/keyboard. I also went ahead and wiped the app data, as well as reinstalled just to make sure I was still consistently encountering this issue. And if I choose to Add an Entry in Bitwarden from a site, it's only capturing the domain/IP and is not including the port in the URI.

**Comment by Safemode** [comment] 2024-11-11 16:12
@david-livefront Have you had any chance to take a look as to why this is still not working? 2024.11.0 (and even up through 2024.11.4 Beta Tester availability) still does not properly show individual Host entries with the Host URI Matching on Android. And adding an entry still cuts off the port and any later URI details. This problem is only happening on Android, the iOS version of the app works exactly as expected with Host URI Matching set as default.

**Comment by uniquePWD** [comment] 2024-11-11 18:18
> 👋🏾 I meant to share an updated earlier but dropped the ball, for which I'm sorry. During our research we concluded that the Autofill Framework isn't sending us the port as expected. While we'll continue to monitor how to provide this functionality, based on your feedback we'll discuss reverting the recent changes and how that will impact other areas of the product.
> 
> Thank you for your feedback and patience 🙏🏾

Any update @vvolkgang

**Comment by vvolkgang** [comment] 2024-11-14 00:02
@Safemode @uniquePWD 👋🏾 In https://github.com/bitwarden/android/issues/3341 we updated our Host matching to include Port validation when available. This worked for me using Accessibility Autofill tile, but the behaviour might vary across different devices, operating systems, and browsers. 

In our testing we never get a Port from Android's Autofill Framework. In these cases, we fall back to IP-only matching to ensure users still get relevant suggestions. You can verify this by initiating the autofill process and adding a new item - the URI received by the app will be visible.

At this point I'm not sure what else we could look into to improve the Autofill Framework support here and I'd welcome any suggestions for improving our Autofill Framework support.

**Comment by uniquePWD** [comment] 2024-11-14 11:03
> @Safemode @uniquePWD 👋🏾 In #3341 we updated our Host matching to include Port validation when available. This worked for me using Accessibility Autofill tile, but the behaviour might vary across different devices, operating systems, and browsers.
> 
> In our testing we never get a Port from Android's Autofill Framework. In these cases, we fall back to IP-only matching to ensure users still get relevant suggestions. You can verify this by initiating the autofill process and adding a new item - the URI received by the app will be visible.
> 
> At this point I'm not sure what else we could look into to improve the Autofill Framework support here and I'd welcome any suggestions for improving our Autofill Framework support.

This has actually worked previously. So it's clearly possible in spite of the AutoFill framework falling short. Are there no native workarounds? What about leveraging the browser extension to provide the host port (URI + port)? Is that a possibility?

**Comment by benkap** [comment] 2024-12-18 19:19
+1
same issue, seems that the port is ignored. 2024.11.7 (not beta... this released to the wild)

**Comment by uniquePWD** [comment] 2025-01-28 08:18
@vvolkgang any updates?

**Comment by manduted** [comment] 2025-01-31 09:07
same issue, seems that the port is ignored 11.5 11.6 12.0 25.1.0 25.1.1

However, the release notes this issue has been fixed..In reality, it did not work.

**Comment by uniquePWD** [comment] 2025-01-31 09:09
Hilariously, it's now doing the exact opposite

**Comment by mycarrysun** [comment] 2025-02-09 14:35
> [@Safemode](https://github.com/Safemode) [@uniquePWD](https://github.com/uniquePWD) 👋🏾 In [#3341](https://github.com/bitwarden/android/issues/3341) we updated our Host matching to include Port validation when available. This worked for me using Accessibility Autofill tile, but the behaviour might vary across different devices, operating systems, and browsers.
> 
> In our testing we never get a Port from Android's Autofill Framework. In these cases, we fall back to IP-only matching to ensure users still get relevant suggestions. You can verify this by initiating the autofill process and adding a new item - the URI received by the app will be visible.
> 
> At this point I'm not sure what else we could look into to improve the Autofill Framework support here and I'd welcome any suggestions for improving our Autofill Framework support.

This has worked fine previously on mobile in android and now with the new redesigned app it does not work. I would consider that a regression so it's not android that's the problem. Maybe we should look at how the legacy app used to detect the host+port?

**Comment by uniquePWD** [comment] 2025-02-09 21:21
Someone just posted something that may be insightful over at https://github.com/bitwarden/clients/issues/9329#issuecomment-2646603294
