### ISSUE TITLE
Missing quicktile option in android quick settings 

### ISSUE THREAD

**Issue by artgru** [bitwarden/android#3744] opened 2024-08-15 08:22 UTC
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Try to add a quicktile icon of the app to the quick settings

### Expected Result

Quicktile button should be available for usage.

### Actual Result

After the newest app update quicktile is broken.
1. Quicktile for the app is gone from the android quick settings icons. So you can't set the app icon for faster access

### Build Version

2024.8.0 (18985)

### Environment Details

Samsung S24 Ultra

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-08-15 09:00
Duplicate of https://github.com/bitwarden/android/issues/3595

**Comment by djsmith85** [comment] 2024-08-15 09:01
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/android/issues/3595 .

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-08-15 09:01 UTC
Labels: bug
