### ISSUE TITLE
Request to reintroduce auto-fill toggle

### ISSUE THREAD

**Issue by singhh9596** [bitwarden/android#3893] opened 2024-09-10 15:24 UTC
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Login screen
2. Enter email from auto fill shortcut 
3. New page for password appears and some times auto fill option doesn't show up.
4. Better to read whole paragraph.

### Expected Result

In such scenarios, user can bring auto fill from the toggles

### Actual Result

Either autofill should be seamless or provide toggle 

### Additional Context

Please reintroduce the status bar toggle for the auto-fill option. On many sites, the auto-fill option on the keyboard doesn’t appear, which forces me to manually copy and paste credentials from the app. This negatively impacts the user experience. The toggle was a key feature that influenced my decision to switch from LastPass to Bitwarden.

### Build Version

2024.8.1

### Environment Details

Redmi k20pro /MI 9T PRO (custom rom based on A14), samsung m42  (one UI 5.1 based on android 13)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-09-10 15:54
Duplicate of https://github.com/bitwarden/android/issues/3595

**Comment by djsmith85** [comment] 2024-09-10 15:54
Hi @singhh9596 !

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/android/issues/3595 .
This issue will now be closed.
Thanks!

**Closed by djsmith85** 2024-09-10 15:54 UTC
Labels: bug
