### ISSUE TITLE
Bitwarden requires force-quitting to reload

### ISSUE THREAD

**Issue by YamiYukiSenpai** [bitwarden/android#4240] opened 2024-11-06 12:45 UTC
### Steps To Reproduce

1. Autofill using the autofill quick settings or the default detection method 

You can also just open the app after leaving it in the background for few hours or something. 

### Expected Result

The app should load my passwords without much fuss.  If it can't sync,  put whatever was there prior to syncing with warning. 

### Actual Result

The app tries to reload like its trying to sync the passwords from the internet before proceeding.

### Additional Context

Disabling autosync seems to help.

### Build Version

2024.10.2 (19397)

### What server are you connecting to?

US

### Environment Details

- Samsung Galaxy Z Flip 6
- Android 14
- Installed from F-Droid

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by freakshock88** [comment] 2024-11-06 19:17
I have a similar issue. A workaround is opening the app manually and force syncing. It seems it get stuck syncing in the backlog or something. I'm using a self hosted server

**Comment by dfunkt** [comment] 2024-11-07 07:49
Sounds like a duplicate of https://github.com/bitwarden/android/issues/3881

**Comment by aj-rosado** [comment] 2024-11-08 14:27
Hi all,
This has been addressed in release 2024.11.3, which is now generally available in PlayStore and our F-Droid repository.

**Closed by aj-rosado** 2024-11-08 14:27 UTC
Labels: bug
