### ISSUE TITLE
Fingerprint scan popup does not show up automatically while app opening 

### ISSUE THREAD

**Issue by artgru** [bitwarden/android#3745] opened 2024-08-15 08:28 UTC
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Try to open the app having finger print unlock option active
2. A popup for Fingerprint scan should show up
3. Instead you need to manually initiate by clicking "Fingerprint unlock" button

### Expected Result

Fingerprint popup should show up autimatically 

### Actual Result

After the update upon app launch the app does not trigger fingerprint popup, now it is required to click the button "biometric unlock" to trigger it. 

### Build Version

2024.8.0 (18985)

### Environment Details

Samsung S24 Ultra

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-08-15 10:28
Duplicate of https://github.com/bitwarden/android/issues/3724

**Comment by djsmith85** [comment] 2024-08-15 10:40
Hi @artgru  and thank you for your report.

This was previously reported with https://github.com/bitwarden/android/issues/3724 and a fix is linked with https://github.com/bitwarden/android/pull/3728 which will be included in a future release.

Closing this now.

Kind regards,
Daniel

**Closed by djsmith85** 2024-08-15 10:40 UTC
Labels: bug
