### ISSUE TITLE
Quick actions don't work

### ISSUE THREAD

**Issue by user-naa** [bitwarden/android#3700] opened 2024-08-08 18:39 UTC
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Hold app in launcher for 2 seconds
2. Release app
3. Tap "Password Generator" or "My vault" option

### Expected Result

Should open selected app page

### Actual Result

Toast appears with text "App isn't installed".

### Build Version

2024.7.3 (18938)

### Environment Details

Android 14

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-08-15 09:10
Duplicate of https://github.com/bitwarden/android/issues/3595

**Comment by djsmith85** [comment] 2024-08-15 09:10
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/android/issues/3595 .

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-08-15 09:10 UTC
Labels: bug
