### ISSUE TITLE
Account unexpectedly logout

### ISSUE THREAD

**Issue by AndrewLauu** [bitwarden/android#4318] opened 2024-11-16 07:41 UTC
### Steps To Reproduce

Account automatically logout frequently even though session timeout has been set as `Never`, and no reboot, no killing the app manually. 

### Expected Result

Keep account logged in according to the setting 

### Actual Result

Logged out frequently 

### Build Version

2024.11.5 (19461)

### What server are you connecting to?

Self-host

### Self-host Server Version

v2024.09.29.1641

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-11-18 14:38
Hello @AndrewLauu,

Thank you for your report. This report seems to be a duplicate of this [GitHub report](https://github.com/bitwarden/clients/issues/10718). Please check that thread out, and espeically [this comment](https://github.com/bitwarden/clients/issues/10718#issuecomment-2479109140); If there's anything you'd like to add, such as logs, screenshots, or video recordings of the screen, please feel free to add them to that existing GitHub report so that they'd be reviewed by the Bitwarden Engineering department.

This report will now be closed as a duplicate.

Thank you again,

**Closed** 2024-11-18 14:38 UTC
Labels: bug
