### ISSUE TITLE
Certen Parts of the UI are in Light Mode

### ISSUE THREAD

**Issue by BryaniEnjoyer** [bitwarden/android#3340] opened 2024-06-23 01:48 UTC
### Steps To Reproduce

1. Open the App
2. On the "My vault" page, click on the 3 dots on the top-right to open a box
3. A box pops up with the options of "Sync", "Lock" and "Exit". 

### Expected Result

When this box shows up, the background of it should be in black since the "My vault" page is black and the app settings shows "Dark mode".

### Actual Result

The background of that box is white.

### Screenshots or Videos

![IMG_20240622_194232](https://github.com/bitwarden/android/assets/142766288/f754c779-53ef-4870-8841-a328661b5c51)

### Build Version

2024.6.0 (10746)

### Environment Details

-Device: Google Pixel 7
-OS: Android 14, Using GrapheneOS

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-06-24 04:34
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by fessmm** [comment] 2024-07-02 11:56
@sammbw this is the old app, not the new one with kotlin.

**Comment by BabyOilJohnson** [comment] 2024-07-10 09:41
This issue was already raised in the legacy app #3090.

**Comment by Hinton** [comment] 2024-07-18 09:57
Hi,

This repository is only for the new native Android application which is currently in beta. Since this seems to be the older Xamarin application and there is already an open issue bitwarden/mobile#3090 I will close this issue.

**Closed by Hinton** 2024-07-18 09:57 UTC
Labels: bug
