### ISSUE TITLE
Error while generating DuckDuckGo Forward Email Username

### ISSUE THREAD

**Issue by zunelol** [bitwarden/android#4226] opened 2024-11-04 11:13 UTC
### Steps To Reproduce

1. Go to 'Generator'
2. Click on 'Username -> make sure DuckDuckGo is selected as provider and an API Key is saved'
4. Click on 'Generate'

### Expected Result

In the generated username field is a newly generated @duck.com email username.

### Actual Result

An error message "Expect rustls-platform-verifier to be initialized" pops up at the bottom of the app (see screenshot)

### Screenshots or Videos

![Screenshot_20241103_193125_com x8bit bitwarden](https://github.com/user-attachments/assets/97eeebd0-e229-418c-b0ca-1c686136b4a3)

### Additional Context

API-Credentials work fine (checked on Bitwarden Extension for Brave on a different device).
Worked on the last App Update (2024.10.x)

### Build Version

2024.11.0 (19415)

### What server are you connecting to?

EU

### Environment Details

- Device: Huawei P30Pro
- OS-Version: Android 10 EMUI 12.0.0.219 (C431E3R2P2)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by noodlejetski** [comment] 2024-11-04 12:49
https://github.com/bitwarden/android/issues/4205#issuecomment-2448233914

**Comment by NovaSilentium** [comment] 2024-11-04 13:45
Duplicate of #4205

**Comment by maxmini1** [comment] 2024-11-05 01:35
Fixes on

https://github.com/user-attachments/assets/45af7fa2-8985-4899-9930-9132097763b7



Version: 2024.11.0 (19421)

**Comment by maxmini1** [comment] 2024-11-05 01:39
Fixes on

https://github.com/user-attachments/assets/b03ca873-be83-4cde-9abb-0fa3b3e1a578



Version: 2024.11.0 (19421)

**Closed** 2024-11-05 13:41 UTC
Labels: bug
