### ISSUE TITLE
First action always so slow on Wi-Fi

### ISSUE THREAD

**Issue by zanaattila** [bitwarden/android#1158] opened 2020-11-23 13:26 UTC
## Describe the Bug
When I open my app, and unlock my vault, the first action (either sync or delete) is really slow, but successful if I wait enough. On mobile data, it's instantly happens. When I close the app fully (so it's not running in the RAM), then I open it again, it happens again.

## Steps To Reproduce

1. Make sure, that you don't have the app running in the background.
2. Open the app. Log in with biometric credentials or master password.
3. Try to sync your vault or delete one element from the trash.
4. Wait for 40-50 secs.
5. Your vault is synced or your element is deleted from trash.

## Expected Result

The expected result would be less waiting time for the action (so, appropriate to the WiFi speed)

## Actual Result
I wait for 40-50 secs, although my speedtest result is 38.7/27.0 mb/s, then my vault is synced or the element is deleted. Then, my vault sync really fast (1-2 secs), and the delete happens immediately.

## Environment

- Device: Huawei CAN-L01 (Huawei Nova)
- Operating system: EMUI 5.0 (Android 7.0)
- Build Version (go to "Settings" → "About" in the app): CAN-L01C150B340
- Is this a Beta release? N

**Comment by i3130002** [comment] 2022-10-03 14:33
Is it a duplicate of https://github.com/bitwarden/mobile/issues/1723 ?

**Comment by vvolkgang** [comment] 2024-06-20 20:54
Issue migrated to https://github.com/bitwarden/mobile/issues/1158

**Closed by vvolkgang** 2024-06-20 20:54 UTC
