### ISSUE TITLE
'<' character is hidden on password input

### ISSUE THREAD

**Issue by serdardal** [bitwarden/android#4507] opened 2024-12-23 20:27 UTC
### Steps To Reproduce

1. Go to any Login type record
2. Click on edit
3. Enter password contains '<' character
4. Click on save
5. Toggle visibility of password or copy
6. '<' character is not there

### Expected Result

Passwords containing the '<' character should be displayed as is.

### Actual Result

'<' character is not visible, not copied to clipboard.

### Build Version

2024.10.0 (11270)

### What server are you connecting to?

EU

### Environment Details

- Device: Samsung Galaxy Note 10 Lite
- Android Version: 13

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment] 2024-12-23 21:47
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/android/issues/3332

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by jtodddd** 2024-12-23 21:47 UTC
Labels: bug
