### ISSUE TITLE
If the URL consists of an IP address and a port number, and the matching pattern is set to the host, it will list all options for that IP address without performing a port number match.

### ISSUE THREAD

**Issue by qiaoyun680** [bitwarden/android#4242] opened 2024-11-06 14:31 UTC
### Steps To Reproduce

If the URL consists of an IP address and a port number, and the matching pattern is set to the host, it will list all options for that IP address without performing a port number match.

### Expected Result

Options should be matched based on both the IP address and the port number.

### Actual Result

It will list all options for the IP, including those that are not for the specified port number.

### Build Version

2024.11.0 (19423)

### What server are you connecting to?

US

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-11-06 15:46
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/android/issues/3341. 
Please note that while that GitHub issue is marked as closed, our engineers are working off of an internal ticket that was generated by that GitHub issue. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2024-11-06 15:46 UTC
Labels: bug

**Comment by qiaoyun680** [comment] 2024-11-06 22:58
> Hi there!
> 
> Thank you for your report, it seems like it is a duplicate of this one #3341. Please note that while that GitHub issue is marked as closed, our engineers are working off of an internal ticket that was generated by that GitHub issue.
> 
> If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.
> 
> This issue will now be closed.
> 
> Thanks!

I have already tried it, and this issue has not been effectively resolved.

**Comment by benkap** [comment] 2024-12-18 19:20
+1
same issue 2024.11.7
