### ISSUE TITLE
Can't type a password length in the generator tab

### ISSUE THREAD

**Issue by flexagoon** [bitwarden/android#3386] opened 2024-06-30 10:51 UTC
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to generator
2. Click on the "length" input

### Expected Result

You should be able to type in the required length with the keyboard 

### Actual Result

Nothing happens, you can only select length with a slider

### Build Version

2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-06-30 11:38
Hi @flexagoon,

Thank you for this report. I recommend that you consider submitting this as an improvement suggestion or feature request in the [Bitwarden Community](https://community.bitwarden.com/c/feature-requests/5), since that is the expected behaviour; Please bear in mind that you'd need to use the slider as well, in version 2024.6.0 of the Android and iOS clients.

I will now close this GitHub report. If you have any questions or concerns, please feel free to get in touch via the form in the Bitwarden [Help Centre](https://bitwarden.com/help/), and please include a link to this GitHub report in your message if you do so.

Thank you again,

**Closed by SergeantConfused** 2024-06-30 11:38 UTC
Labels: bug
